
# File created automatically by 'mt-tgadmin init' command. There are all available
# options listed here with its default values. Recommendation is to edit options you
# want to change and remove all others to keep this as simple as possible.
#
# Created on: 2022-11-11T15:46:52+03:00
#

# Bot authorization token
bot_token: "5745757811:AADOGQhUinxdvNСlXUРSZGВ0vlrd_qхWlR0"

# GUI cookie secret key
gui_cookie_secret_key: "Please change this in production environment"

# GUI access password
gui_password: "mitoteam"
# Web GUI hostname
gui_hostname: "localhost"
# Web GUI port number
gui_port: 15080
